package pipe.gui.widgets.newwidges;

import org.jdom.Element;
import pipe.gui.ApplicationSettings;

import javax.swing.*;
import java.util.*;
import java.util.regex.Pattern;

/**
 * Created by hanson on 2017/8/22.
 * 建模向导第三步，选择每个SPM分区中虚链路的数量
 */

public class ModelGuideDialog3 extends JDialog {
    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    //添加备注button
    //private javax.swing.JButton jButtonArray6[] = new javax.swing.JButton[100];

    private javax.swing.JButton jButtonNextStep;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;

    private javax.swing.JButton jButton6;

    private javax.swing.JComboBox jComboBox10;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;

    //第一列的编号
    private javax.swing.JLabel[] jLabelArray1 = new javax.swing.JLabel[100];

    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabe20;
    private javax.swing.JLabel jLabe21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;

    //第二列 ID
    private JTextField[] jTextFieldArray2 = new JTextField[100];

    //第三列 分区1中VL数量
    private JTextField[] jTextFieldArray3 = new JTextField[100];

    //第四列  分区2中VL数量
    private JTextField[] jTextFieldArray4 = new JTextField[100];

    //第五列  分区3中VL数量
    private JTextField[] jTextFieldArray5 = new JTextField[100];

    //第6列  轮训周期
    private JTextField[] jTextFieldArray6 = new JTextField[100];

    // End of variables declaration
    private int returnStatus = RET_CANCEL;

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    private GuideModel nowModel;

    private String[] id = new String[100];
    private int[] lxPeriod = new int[100];

    private Integer[] Par1VLNumber = new Integer[100];
    private Integer[] Par2VLNumber = new Integer[100];
    private Integer[] Par3VLNumber = new Integer[100];
    /** Creates new form ModelGuideDialog1 */
    public ModelGuideDialog3(java.awt.Frame parent, boolean modal,GuideModel guideModel) {

        super(parent, modal);
        nowModel = guideModel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        int num = nowModel.getNumOfSPM();
        setResizable(false);

        for(int i=0; i<num; i++)
        {
            jLabelArray1[i] = new javax.swing.JLabel();
            jTextFieldArray2[i] = new JTextField();
            jTextFieldArray3[i] = new JTextField();
            jTextFieldArray4[i] = new JTextField();
            jTextFieldArray5[i] = new JTextField();
            jTextFieldArray6[i] = new JTextField();
            //jButtonArray6[i] = new JButton();
        }
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonNextStep = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();


        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabe20 = new javax.swing.JLabel();
        jLabe21 = new javax.swing.JLabel();

        jButton6.setText("添加备注");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("建模向导");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("第二步");

        jLabel2.setText("  选择每个SPM分区中虚链路的数量");

        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_guide.png"))); // NOI18N
        //jLabel3.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//            jPanel1Layout.setAutoCreateGaps(true);
//            jPanel1Layout.setAutoCreateContainerGaps(true);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jButtonNextStep.setText("下一步");
        jButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextStepActionPerformed(evt);
            }
        });

        jButton3.setText("取消");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("上一步");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevStepActionPerformed(evt);
            }
        });

        jLabel5.setText("编号");
        jLabel7.setText("SPM_ID");
        jLabel8.setText("分区1中VL数量");
        jLabel9.setText("分区2中VL数量");
        jLabe20.setText("分区3中VL数量");
        jLabe21.setText("传输周期");
        //这块一下把十个都设置好吧  然后 这里4-10的响应函数 没调整呢 注意

        for(int i=0; i<num; i++)
        {
            jLabelArray1[i].setText("   "+(i+1));
            // 	jTextFieldArray2[i].setActionCommand("jTextFieldArray2_"+(i));
            jTextFieldArray2[i].setText("SPM"+(i+1)+"_");
            jTextFieldArray2[i].addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTextField2_1FocusLost(evt);
                }
            });
            /* TODO
            jComboBoxArray3[i].setModel(new javax.swing.DefaultComboBoxModel(new String[] { "周期型", "事件型" }));
            jComboBoxArray3[i].setActionCommand("jComboBoxArray_"+(i));
            jComboBoxArray3[i].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox3_1ActionPerformed(evt);
                }
            });*/
            jTextFieldArray3[i].setText("1");
            //jTextFieldArray4[i].setToolTipText("周期：单位ms");

            jTextFieldArray4[i].setText("1");

            jTextFieldArray5[i].setText("1");

        }

        javax.swing.GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2Layout.setAutoCreateGaps(true);
        jPanel2Layout.setAutoCreateContainerGaps(true);
        jPanel2.setLayout(jPanel2Layout);
        GroupLayout.ParallelGroup gp1 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp1.addComponent(jLabel5);
        for(int i=0; i<num; i++)
        {
            gp1.addComponent(jLabelArray1[i]);
        }
//            gp1.addComponent(jLabel1_1);
//            gp1.addComponent(jLabel1_2);
//            gp1.addComponent(jLabel1_3);

        GroupLayout.ParallelGroup gp2 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp2.addComponent(jLabel7);
        for(int i=0; i<num; i++)
        {
            gp2.addComponent(jTextFieldArray2[i]);
        }
//            gp2.addComponent(jTextField2_1);
//            gp2.addComponent(jTextField2_2);
//            gp2.addComponent(jTextField2_3);

        GroupLayout.ParallelGroup gp3 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp3.addComponent(jLabel8);
        for(int i=0; i<num; i++)
        {
            gp3.addComponent(jTextFieldArray3[i]);
        }

        GroupLayout.ParallelGroup gp4 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp4.addComponent(jLabel9);
        for(int i=0; i<num; i++)
        {
            gp4.addComponent(jTextFieldArray4[i]);
        }
//            gp4.addComponent(jTextField4_1,javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE);
//            gp4.addComponent(jTextField4_2,javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE);
//            gp4.addComponent(jTextField4_3,javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE);

        GroupLayout.ParallelGroup gp5 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp5.addComponent(jLabe20);
        for(int i=0; i<num; i++)
        {
            gp5.addComponent(jTextFieldArray5[i]);
        }
        GroupLayout.ParallelGroup gp55 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp55.addComponent(jLabe21);
        for(int i=0; i<num; i++)
        {
            jTextFieldArray6[i].setText("100");
            gp55.addComponent(jTextFieldArray6[i]);
        }

        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(gp1).addGap(30).addGroup(gp2).addGap(30).addGroup(gp3).addGap(30).addGroup(gp4).addGap(30).addGroup(gp5).addGap(30).addGroup(gp55));


        GroupLayout.ParallelGroup gp6 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE);
        gp6.addComponent(jLabel5);
        gp6.addComponent(jLabel7);
        gp6.addComponent(jLabel8);
        gp6.addComponent(jLabel9);
        gp6.addComponent(jLabe20);
        gp6.addComponent(jLabe21);
        GroupLayout.SequentialGroup group = jPanel2Layout.createSequentialGroup().addGroup(gp6);

        for(int i=0; i<num; i++)
        {
            //System.out.println("284 num:" + num);
            GroupLayout.ParallelGroup gpTemp = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE);
            gpTemp.addComponent(jLabelArray1[i]);
            gpTemp.addComponent(jTextFieldArray2[i]);
            gpTemp.addComponent(jTextFieldArray3[i]);
            gpTemp.addComponent(jTextFieldArray4[i]);
            gpTemp.addComponent(jTextFieldArray5[i]);
            gpTemp.addComponent(jTextFieldArray6[i]);
            group.addGroup(gpTemp);
        }

        jPanel2Layout.setVerticalGroup(group);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(318, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNextStep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(8, 8, 8))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButtonNextStep)
                                        .addComponent(jButton4))
                                .addContainerGap())
        );
        pack();

    }// </editor-fold>


    private void jTextField2_1FocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        //    	System.out.println(command+"||||||||||||||||||||");//这里原本想 失去焦点 然后判断是否重复  但是因为不知道这个事件是哪个 textField发出来的 所以作罢

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }

    private void jButtonPrevStepActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //上一步
        int num = nowModel.getNumOfSPM();
        for(int i=0; i<num; i++)
        {
            id[i] = jTextFieldArray2[i].getText().trim();
            lxPeriod[i] = Integer.parseInt(jTextFieldArray6[i].getText().trim());
            //System.out.println("33333333333333"+jTextFieldArray6[i].getText().trim() +","+ lxPeriod[i]);
        }

        for(int i=0; i<num; i++)
        {
            if(jTextFieldArray3[i].getText().trim().equals(""))
                Par1VLNumber[i]=0;
            else
                Par1VLNumber[i] = Integer.parseInt(jTextFieldArray3[i].getText());

            if(jTextFieldArray4[i].getText().trim().equals(""))
                Par2VLNumber[i]=0;
            else
                Par2VLNumber[i] = Integer.parseInt(jTextFieldArray4[i].getText());

            if(jTextFieldArray5[i].getText().trim().equals(""))
                Par3VLNumber[i]=0;
            else
                Par3VLNumber[i] = Integer.parseInt(jTextFieldArray5[i].getText());
        }

        Queue<SPM> spmList = new LinkedList<SPM>();
        for(int i=0; i<num; i++)
        {
           SPM spm = new SPM();
           spm.setId(this.id[i]);
           spm.setLxPeriod(lxPeriod[i]);
           spm.setPar1VLNum(this.Par1VLNumber[i]);
           spm.setPar2VLNum(this.Par2VLNumber[i]);
           spm.setPar3VLNum(this.Par3VLNumber[i]);
           spm.setPARTITION1(new Paratition(this.id[i] + "Par1_"));
           spm.setPARTITION2(new Paratition(this.id[i] + "Par2_"));
           spm.setPARTITION3(new Paratition(this.id[i] + "Par3_"));
           spmList.add(spm);
        }

        this.nowModel.setSpmList(spmList);
        doClose(RET_CANCEL);
        ModelGuideDialog2 guiDialog1 =  new ModelGuideDialog2(ApplicationSettings.getApplicationView(), true, this.nowModel);
        guiDialog1.pack();
        guiDialog1.setLocationRelativeTo(null);
        guiDialog1.setVisible(true);
    }

    private void jButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        int num = nowModel.getNumOfSPM();

        for(int i=0; i<num; i++)
        {
            id[i] = jTextFieldArray2[i].getText().trim();
            lxPeriod[i] = Integer.parseInt(jTextFieldArray6[i].getText().trim());
            if(id[i].equals(""))
            {
                JOptionPane.showMessageDialog(this, "ID不能为空", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        for(int i=0; i<num; i++)
        {
            if(jTextFieldArray3[i].getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "参数不能为空", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Par1VLNumber[i] = Integer.parseInt(jTextFieldArray3[i].getText());

            if(jTextFieldArray4[i].getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "参数不能为空", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Par2VLNumber[i] = Integer.parseInt(jTextFieldArray4[i].getText());

             if(jTextFieldArray5[i].getText().trim().equals(""))
                {
                    JOptionPane.showMessageDialog(this, "参数不能为空", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Par3VLNumber[i] = Integer.parseInt(jTextFieldArray5[i].getText());
        }
        Queue<SPM> spmList = new LinkedList<SPM>();
        for(int i=0; i<num; i++)
        {
            SPM spm = new SPM();
            spm.setId(this.id[i]);
            spm.setLxPeriod(lxPeriod[i]);
           // System.out.println("3333333lxPeriod:"+lxPeriod);
            spm.setPar1VLNum(this.Par1VLNumber[i]);
            spm.setPar2VLNum(this.Par2VLNumber[i]);
            spm.setPar3VLNum(this.Par3VLNumber[i]);
            spm.setPARTITION1(new Paratition(this.id[i] + "Par1_"));
            spm.setPARTITION2(new Paratition(this.id[i] + "Par2_"));
            spm.setPARTITION3(new Paratition(this.id[i] + "Par3_"));
            spmList.add(spm);
        }

        this.nowModel.setSpmList(spmList);

        doClose(RET_OK);
    	ModelGuideDialog4 guiDialog =  new ModelGuideDialog4(ApplicationSettings.getApplicationView(), true, this.nowModel);
        guiDialog.pack();
        guiDialog.setLocationRelativeTo(null);
        guiDialog.setVisible(true);
    }
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModelGuideDialog1 dialog = new ModelGuideDialog1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
}
